{% set name = "lerc" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Esri/lerc/archive/v{{ version }}.tar.gz
  sha256: 91431c2b16d0e3de6cbaea188603359f87caed08259a645fd5a3805784ee30a0
  # CMakeLists.txt taken from master, and adapted for better compatibility
  # PR made: https://github.com/Esri/lerc/pull/128
  patches:
    # see https://github.com/Esri/lerc/issues/253
    - add-missing-include.patch

build:
  number: 0
  run_exports:
    # No real information, keep conda-forge defaults
    - {{ pin_subpackage('lerc', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - ninja-base  # [win]
    - m2-patch    # [win]
    - patch       # [unix]

test:
  commands:
    - if not exist %LIBRARY_INC%\Lerc_types.h exit 1  # [win]
    - if not exist %LIBRARY_INC%\Lerc_c_api.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\Lerc.dll exit 1      # [win]
    - if not exist %LIBRARY_LIB%\Lerc.lib exit 1      # [win]
    - if not exist %LIBRARY_LIB%\pkgconfig\Lerc.pc exit 1      # [win]
    - test -f ${PREFIX}/lib/libLerc${SHLIB_EXT}       # [unix]
    - test -f ${PREFIX}/include/Lerc_types.h          # [unix]
    - test -f ${PREFIX}/include/Lerc_c_api.h          # [unix]
    - test -f ${PREFIX}/lib/pkgconfig/Lerc.pc         # [unix]

about:
  home: https://github.com/Esri/lerc
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: LERC - Limited Error Raster Compression
  description: |
    LERC is an open-source image or raster format which
    supports rapid encoding and decoding for any pixel type
    (not just RGB or Byte). Users set the maximum compression
    error per pixel while encoding, so the precision of the
    original input image is preserved (within user defined
    error bounds).
  dev_url: https://github.com/Esri/lerc
  doc_url: https://github.com/Esri/lerc

extra:
  recipe-maintainers:
    - hmaarrfk
